trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndTest
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        dotnet restore L4D2PlayStats.Web/L4D2PlayStats.Web/L4D2PlayStats.Web.csproj
      displayName: 'Restore NuGet Packages'

    - script: |
        dotnet build L4D2PlayStats.Web/L4D2PlayStats.Web/L4D2PlayStats.Web.csproj --configuration Release
      displayName: 'Build Project'

    - script: |
        dotnet test L4D2PlayStats.Web/L4D2PlayStats.Web/L4D2PlayStats.Web.csproj --configuration Release
      displayName: 'Run Unit Tests'

- stage: PublishAndDeploy
  dependsOn: BuildAndTest
  jobs:
  - job: Publish
    steps:

    - script: |
        dotnet restore L4D2PlayStats.Web/L4D2PlayStats.Web/L4D2PlayStats.Web.csproj
      displayName: 'Restore NuGet Packages'

    - script: |
        mkdir -p $(Build.ArtifactStagingDirectory)/publish/pt-BR
        mkdir -p $(Build.ArtifactStagingDirectory)/publish/es-ES
      displayName: 'Create directories'

    - script: |
        dotnet publish L4D2PlayStats.Web/L4D2PlayStats.Web/L4D2PlayStats.Web.csproj -c Release -o $(Build.ArtifactStagingDirectory)/publish
      displayName: 'Publish Project'

    - script: |
        tar -czf publish.tar.gz -C $(Build.ArtifactStagingDirectory)/publish .
      displayName: 'Compress Published Files'

    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'L4D2'
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        contents: 'publish.tar.gz'
        targetFolder: '/home/devops'
        cleanTargetFolder: false
        overwrite: true
        readyTimeout: '20000'

    - task: SSH@0
      inputs:
        sshEndpoint: 'L4D2'
        readyTimeout: '20000'
        runOptions: 'script'
        scriptPath: 'scripts/deploy.sh'