trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndTest
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: '📦 Install .NET 9 SDK'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        dotnet restore L4D2PlayStats.Web/L4D2PlayStats.Web/L4D2PlayStats.Web.csproj
      displayName: '🔄 Restore NuGet Packages'

    - script: |
        dotnet build L4D2PlayStats.Web/L4D2PlayStats.Web/L4D2PlayStats.Web.csproj --configuration Release
      displayName: '🏗️ Build Project'

- stage: PublishAndDeploy
  dependsOn: BuildAndTest
  jobs:
  - job: Publish
    steps:
    - task: UseDotNet@2
      displayName: '📦 Install .NET 9 SDK'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        dotnet restore L4D2PlayStats.Web/L4D2PlayStats.Web/L4D2PlayStats.Web.csproj
      displayName: '🔄 Restore NuGet Packages'

    - script: |
        mkdir -p $(Build.ArtifactStagingDirectory)/publish/pt-BR
        mkdir -p $(Build.ArtifactStagingDirectory)/publish/es-ES
      displayName: '📂 Create Directories'

    - script: |
        dotnet publish L4D2PlayStats.Web/L4D2PlayStats.Web/L4D2PlayStats.Web.csproj -c Release -o $(Build.ArtifactStagingDirectory)/publish
      displayName: '🚀 Publish Project'

    - script: |
        tar -czf bash.tar.gz -C $(Build.Repository.LocalPath)/bash .
        tar -czf publish.tar.gz -C $(Build.ArtifactStagingDirectory)/publish .
      displayName: '🗜️ Compress Published Files'

    - task: CopyFilesOverSSH@0
      displayName: '📤 Copy Files Over SSH'
      inputs:
        sshEndpoint: 'L4D2 - Resources'
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        contents: '*.tar.gz'
        targetFolder: '/home/devops'
        cleanTargetFolder: false
        overwrite: true
        readyTimeout: '20000'

    - task: SSH@0
      displayName: '📦 Extract Files'
      inputs:
        sshEndpoint: 'L4D2 - Resources'
        readyTimeout: '20000'
        runOptions: 'script'
        scriptPath: 'scripts/deploy.sh'
