namespace L4D2PlayStats.Core.Campaign;

public class CampaignName : ICampaignName
{
    private static readonly Dictionary<string, string> Maps = new()
    {
        { "c1m1_hotel", "Dead Center" },
        { "c1m2_streets", "Dead Center" },
        { "c1m3_mall", "Dead Center" },
        { "c1m4_atrium", "Dead Center" },
        { "c2m1_highway", "Dark Carnival" },
        { "c2m2_fairgrounds", "Dark Carnival" },
        { "c2m3_coaster", "Dark Carnival" },
        { "c2m4_barns", "Dark Carnival" },
        { "c2m5_concert", "Dark Carnival" },
        { "c3m1_plankcountry", "Swamp Fever" },
        { "c3m2_swamp", "Swamp Fever" },
        { "c3m3_shantytown", "Swamp Fever" },
        { "c3m4_plantation", "Swamp Fever" },
        { "c4m1_milltown_a", "Hard Rain" },
        { "c4m2_sugarmill_a", "Hard Rain" },
        { "c4m3_sugarmill_b", "Hard Rain" },
        { "c4m4_milltown_b", "Hard Rain" },
        { "c4m5_milltown_escape", "Hard Rain" },
        { "c5m1_waterfront", "The Parish" },
        { "c5m2_park", "The Parish" },
        { "c5m3_cemetery", "The Parish" },
        { "c5m4_quarter", "The Parish" },
        { "c5m5_bridge", "The Parish" },
        { "c6m1_riverbank", "The Passing" },
        { "c6m2_bedlam", "The Passing" },
        { "c7m1_docks", "The Passing" },
        { "c7m2_barge", "The Passing" },
        { "c7m3_port", "The Sacrifice" },
        { "c8m1_apartment", "No Mercy" },
        { "c8m2_subway", "No Mercy" },
        { "c8m3_sewers", "No Mercy" },
        { "c8m4_interior", "No Mercy" },
        { "c8m5_rooftop", "No Mercy" },
        { "c9m1_alleys", "Crash Course" },
        { "c9m2_lots", "Crash Course" },
        { "c14m1_junkyard", "Crash Course" },
        { "c14m2_lighthouse", "Crash Course" },
        { "c10m1_caves", "Death Toll" },
        { "c10m2_drainage", "Death Toll" },
        { "c10m3_ranchhouse", "Death Toll" },
        { "c10m4_mainstreet", "Death Toll" },
        { "c10m5_houseboat", "Death Toll" },
        { "c11m1_greenhouse", "Dead Air" },
        { "c11m2_offices", "Dead Air" },
        { "c11m3_garage", "Dead Air" },
        { "c11m4_terminal", "Dead Air" },
        { "c11m5_runway", "Dead Air" },
        { "c12m1_hilltop", "Blood Harvest" },
        { "c12m2_traintunnel", "Blood Harvest" },
        { "c12m3_bridge", "Blood Harvest" },
        { "c12m4_barn", "Blood Harvest" },
        { "c12m5_cornfield", "Blood Harvest" },
        { "c13m1_alpinecreek", "Cold Stream" },
        { "c13m2_southpinestream", "Cold Stream" },
        { "c13m3_memorialbridge", "Cold Stream" },
        { "c13m4_cutthroatcreek", "Cold Stream" },
        { "dkr_m1_motel", "Dark Carnival Remix" },
        { "dkr_m2_carnival", "Dark Carnival Remix" },
        { "dkr_m3_tunneloflove", "Dark Carnival Remix" },
        { "dkr_m4_ferris", "Dark Carnival Remix" },
        { "dkr_m5_stadium", "Dark Carnival Remix" },
        { "x1m1_cliffs", "Open Road" },
        { "x1m2_path", "Open Road" },
        { "x1m3_city", "Open Road" },
        { "x1m4_forest", "Open Road" },
        { "x1m5_salvation", "Open Road" },
        { "cdta_01detour", "Detour Ahead" },
        { "cdta_02road", "Detour Ahead" },
        { "cdta_03warehouse", "Detour Ahead" },
        { "cdta_04onarail", "Detour Ahead" },
        { "cdta_05finalroad", "Detour Ahead" },
        { "AirCrash", "Heaven Can Wait" },
        { "RiverMotel", "Heaven Can Wait" },
        { "OutSkirts", "Heaven Can Wait" },
        { "CityHall", "Heaven Can Wait" },
        { "BombShelter", "Heaven Can Wait" },
        { "cwm1_intro", "Carried Off" },
        { "cwm2_warehouse", "Carried Off" },
        { "cwm3_drain", "Carried Off" },
        { "cwm4_building", "Carried Off" },
        { "damitdc1", "Dam It! The Director's Cut" },
        { "damitdc2", "Dam It! The Director's Cut" },
        { "damitdc3", "Dam It! The Director's Cut" },
        { "damitdc4", "Dam It! The Director's Cut" },
        { "dprm1_milltown_a", "Hard Rain: Downpour" },
        { "dprm2_sugarmill_a", "Hard Rain: Downpour" },
        { "dprm3_sugarmill_b", "Hard Rain: Downpour" },
        { "dprm4_milltown_b", "Hard Rain: Downpour" },
        { "dprm5_milltown_escape", "Hard Rain: Downpour" },
        { "hf01_theforest", "Haunted Forest" },
        { "hf02_thesteeple", "Haunted Forest" },
        { "hf03_themansion", "Haunted Forest" },
        { "hf04_escape", "Haunted Forest" },
        { "jsarena201_town", "Arena of the Dead 2" },
        { "jsarena202_alley", "Arena of the Dead 2" },
        { "jsarena203_roof", "Arena of the Dead 2" },
        { "jsarena204_arena", "Arena of the Dead 2" },
        { "l4d_dbd2dc_anna_is_gone", "Dead Before Dawn DC" },
        { "l4d_dbd2dc_the_mall", "Dead Before Dawn DC" },
        { "l4d_dbd2dc_clean_up", "Dead Before Dawn DC" },
        { "l4d_dbd2dc_undead_center", "Dead Before Dawn DC" },
        { "l4d_dbd2dc_new_dawn", "Dead Before Dawn DC" },
        { "l4d_ihm01_forest", "I Hate Mountains 2" },
        { "l4d_ihm02_manor", "I Hate Mountains 2" },
        { "l4d_ihm03_underground", "I Hate Mountains 2" },
        { "l4d_ihm04_lumberyard", "I Hate Mountains 2" },
        { "l4d_ihm05_lakeside", "I Hate Mountains 2" },
        { "l4d_tbm_1", "The Bloody Moors" },
        { "l4d_tbm_2", "The Bloody Moors" },
        { "l4d_tbm_3", "The Bloody Moors" },
        { "l4d_tbm_4", "The Bloody Moors" },
        { "l4d_tbm_5", "The Bloody Moors" },
        { "l4d_yama_1", "Yama" },
        { "l4d_yama_2", "Yama" },
        { "l4d_yama_3", "Yama" },
        { "l4d_yama_4", "Yama" },
        { "l4d_yama_5", "Yama" },
        { "l4d2_bts01_forest", "Back to School" },
        { "l4d2_bts02_station", "Back to School" },
        { "l4d2_bts03_town", "Back to School" },
        { "l4d2_bts04_cinema", "Back to School" },
        { "l4d2_bts05_church", "Back to School" },
        { "l4d2_bts06_school", "Back to School" },
        { "l4d2_darkblood01_tanker", "Dark Blood 2" },
        { "l4d2_darkblood02_engine", "Dark Blood 2" },
        { "l4d2_darkblood03_platform", "Dark Blood 2" },
        { "l4d2_darkblood04_extraction", "Dark Blood 2" },
        { "l4d2_diescraper1_apartment_361", "Diescraper Redux" },
        { "l4d2_diescraper2_streets_361", "Diescraper Redux" },
        { "l4d2_diescraper3_mid_361", "Diescraper Redux" },
        { "l4d2_diescraper4_top_361", "Diescraper Redux" },
        { "l4d2_stadium1_apartment", "Suicide Blitz 2" },
        { "l4d2_stadium2_riverwalk", "Suicide Blitz 2" },
        { "l4d2_stadium3_city1", "Suicide Blitz 2" },
        { "l4d2_stadium4_city2", "Suicide Blitz 2" },
        { "l4d2_stadium5_stadium", "Suicide Blitz 2" },
        { "srocchurch", "Warcelona" },
        { "plaza_espana", "Warcelona" },
        { "maria_cristina", "Warcelona" },
        { "mnac", "Warcelona" },
        { "uf1_boulevard", "Urban Flight" },
        { "uf2_rooftops", "Urban Flight" },
        { "uf3_harbor", "Urban Flight" },
        { "uf4_airfield", "Urban Flight" },
        { "uz_crash", "The Undead Zone" },
        { "uz_town", "The Undead Zone" },
        { "uz_desert", "The Undead Zone" },
        { "uz_bunker", "The Undead Zone" },
        { "uz_escape", "The Undead Zone" },
        { "versus_1", "Firetower Trail" },
        { "versus_2", "Firetower Trail" },
        { "versus_3", "Firetower Trail" },
        { "versus_4", "Firetower Trail" },
        { "versus_5", "Firetower Trail" }
    };

    public string? this[string? map]
    {
        get
        {
            if (string.IsNullOrEmpty(map) || !Maps.TryGetValue(map, out var campaign))
                return null;

            return campaign;
        }
    }
}